name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.8.0
    - name: Docker Login
      uses: docker/login-action@v3.3.0
      with:
        username: ivanfarina08
        password: ${{ secrets.SENHA_DOCKER }}
    - name: Build the Docker image
      run: docker build -t "ivanfarina08/ubuntu/go" . --file Dockerfile --tag my-image-name:$(date +%s)

        
