name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: setup Docker Build
      uses: docker/setup-buildx-action@v3
      
    - name: Download a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: programa-${{ github.run_id }}
        path: main
      
    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ivanfarina08
        password: ${{ secrets.SENHA_DOCKER }}
        
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ivanfarina08/go_ci:1.0