name: Go CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build Database Services
      run: docker-compose build

    - name: Start Database Services
      run: docker-compose up -d

    - name: Wait for PostgreSQL to be Ready
      run: |
        for i in {1..10}; do
          if docker exec $(docker ps -qf "name=postgres") pg_isready -U root; then
            echo "PostgreSQL is ready";
            exit 0;
          fi;
          echo "Waiting for PostgreSQL...";
          sleep 5;
        done;
        echo "PostgreSQL failed to start";
        exit 1;

    - name: Run Tests
      env:
        DATABASE_URL: "postgresql://root:root@localhost:5432/root"
      run: go test ./... -v

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build Application
      run: go build -v main.go
